# Generated by Django 4.0.5 on 2022-09-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('ordered_date', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('ordered', models.BooleanField(default=False, verbose_name='Завершен')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Конечная стоимость')),
                ('delivery_time', models.TimeField(blank=True, verbose_name='Время доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Предмет заказа',
                'verbose_name_plural': 'Предметы заказа',
            },
        ),
    ]
