# Generated by Django 4.0.5 on 2022-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
